### ISSUE TITLE
Old options and post type migration

### ISSUE THREAD

**Issue by lebleut** [lebleut/Tooltipy-OOP#2]
Pass to new options then remove old options and post meta

**Comment by lebleut** [comment]
consider also the new post type instead of the old one "**my_keywords**" to allow a whole safe migration

From "**my_keywords**" to "**tooltipy**"

**Comment by lebleut** [comment]
https://github.com/lebleut/Tooltipy-OOP/commit/a60610719f60305c577a496e8d71015564f912c9

**Comment by Yabukism** [comment]
I installed 'migration', but nothing happened. What else is needed to move old options and post types?

**Comment by lebleut** [comment]
Not sure if we need to migrate the general options too or it's up to the user to do

**Comment by lebleut** [comment]
Done : https://github.com/lebleut/Tooltipy-OOP/commit/70744f382107ca29fae9efaf4529950bcab5cc42

**Comment by lebleut** [comment]
Screenshot :
![Selection_348](https://user-images.githubusercontent.com/5214629/90991500-798cfe00-e5a1-11ea-9f59-4204103d3781.png)
