### ISSUE TITLE
Warning: call_user_func() 

### ISSUE THREAD

**Issue by anyway** [lebleut/Tooltipy-OOP#26]
In the admin area in the right sidebar an error message is issued:

![Bildschirmfoto 2020-04-18 um 08 02 14](https://user-images.githubusercontent.com/1565766/79629708-ffa8bc00-814b-11ea-8bc1-cd15f018b78f.png)

**Comment by anyway** [comment]
You can delete this issue completely. This had nothing to do with the plugin. Sorry about the false report.

**Comment by lebleut** [comment]
ok thanks for letting me know
