### ISSUE TITLE
compatibility error with Subscribe to Comments reloaded

### ISSUE THREAD

**Issue by Li-An** [lebleut/Tooltipy-OOP#49]
For some reason, when I go to subscription management page of Subscribe to Comments reloades I have this error

`Toopltipy error
Fatal error: Uncaught Error: Call to a member function find() on bool in /home/jmmeyer00/www/echodesplugins/wp-content/plugins/Tooltipy-OOP-master/public/class-tooltipy-public.php:385 Stack trace: #0 /home/jmmeyer00/www/echodesplugins/wp-content/plugins/Tooltipy-OOP-master/public/class-tooltipy-public.php(372): Tooltipy\Tooltipy_Public->text_nodes_replace(Array, Array, '', 1) #1 /home/jmmeyer00/www/echodesplugins/wp-includes/class-wp-hook.php(307): Tooltipy\Tooltipy_Public->filter_content('') #2 /home/jmmeyer00/www/echodesplugins/wp-includes/plugin.php(189): WP_Hook->apply_filters('', Array) #3 /home/jmmeyer00/www/echodesplugins/wp-includes/formatting.php(3865): apply_filters('the_content', '') #4 /home/jmmeyer00/www/echodesplugins/wp-includes/class-wp-hook.php(307): wp_trim_excerpt('', Object(WP_Post)) #5 /home/jmmeyer00/www/echodesplugins/wp-includes/plugin.php(189): WP_Hook->apply_filters('', Array) #6 /home/jmmeyer00/www/echodesplugins/wp-includes/post-template.php(429): apply_filters('get_the_excerpt', '', Object(WP_ in /home/jmmeyer00/www/echodesplugins/wp-content/plugins/Tooltipy-OOP-master/public/class-tooltipy-public.php on line 385`

It seems to work on a blog test without error so I’m quite puzzled.

**Comment by lebleut** [comment]
Can you tell me about the PHP versions for both sites (your site and the blog test) ?

**Comment by lebleut** [comment]
if the same, please try to make this change in the related file : https://github.com/lebleut/Tooltipy-OOP/commit/8254ad8ebd7194c5dc9577fca59693fbfaf1b826

**Comment by Li-An** [comment]
There is a differcence : the test site is in php 8.0.10 (the site without error) and the site with problem is in php 7.4.27

**Comment by lebleut** [comment]
ok, have you tested with the change I mentioned above ?

**Comment by Li-An** [comment]
OK, it seems fixed with the new code.

**Comment by lebleut** [comment]
Great
